project:
  type: website
  execute-dir: project
  output-dir: _site

website:
  title: "Rip Current Dye Tracking – Long Beach, BC"
  navbar: false
  search: false
  page-navigation: false

format:
  html:
    theme: lux
    css: styles.css
    toc: false

execute:
  echo: false
  freeze: false
